vim.keymap.set({ "n", "x" }, "j", [[v:count == 0 ? 'gj' : 'j']], { expr = true })
vim.keymap.set({ "n", "x" }, "k", [[v:count == 0 ? 'gk' : 'k']], { expr = true })
vim.keymap.set("n", "]b", "<cmd>bnext<cr>", { desc = "Next" })
vim.keymap.set("n", "[b", "<cmd>bprevious<cr>", { desc = "Previous" })
vim.keymap.set("n", "<leader>b", ":ls<cr>:b ", { desc = "List and switch buffers" })
vim.keymap.set("n", "<BS>", "<C-^>", { desc = "Alternate file" })
vim.keymap.set("n", ">", ">>")
vim.keymap.set("n", "<", "<<")
vim.keymap.set("v", ">", ">gv")
vim.keymap.set("v", "<", "<gv")
vim.keymap.set("v", "y", "ygv<esc>")
vim.keymap.set({ "n", "t" }, "<C-h>", "<Cmd>wincmd h<CR>", { desc = "Left" })
vim.keymap.set({ "n", "t" }, "<C-j>", "<Cmd>wincmd j<CR>", { desc = "Down" })
vim.keymap.set({ "n", "t" }, "<C-k>", "<Cmd>wincmd k<CR>", { desc = "Up" })
vim.keymap.set({ "n", "t" }, "<C-l>", "<Cmd>wincmd l<CR>", { desc = "Right" })
vim.keymap.set("t", "<esc>", "<c-\\><c-n>", { desc = "Normal mode" })
vim.keymap.set("n", "<esc>", ":noh<cr><esc>", { desc = "Clear search highlights" })
vim.keymap.set("n", "<leader>oo", ":silent !open .<cr>", { desc = "Open finder" })
vim.keymap.set("n", "<leader>q", vim.diagnostic.setloclist, { desc = "Open quickfix list" })
vim.keymap.set("n", "<leader>e", ":Lexplore<cr>", { desc = "File explorer" })
vim.keymap.set("n", "<leader>v", ":e $MYVIMRC<cr>", { desc = "Edit Neovim config" })
vim.keymap.set("n", "<leader>cd", ":cd %:h<cr>", { desc = "Change dir to current file" })

-- Readline keys
vim.keymap.set("i", "<C-b>", "<left>", { desc = "Left" })
vim.keymap.set("i", "<C-f>", "<right>", { desc = "Right" })
vim.keymap.set("i", "<C-a>", "<home>", { desc = "Append" })
vim.keymap.set("i", "<C-e>", "<end>", { desc = "End" })
vim.keymap.set("i", "<C-d>", "<del>", { desc = "Delete" })
vim.keymap.set("i", "<C-k>", "<C-o>D", { desc = "Delete to end of line" })
